routes/web.php
<?php

use App\Http\Controllers\Auth\GoogleLoginController;
use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Dashboard\DoctorController;
use App\Http\Controllers\Dashboard\SectionController;
use App\Http\Controllers\Dashboard\SingleServiceController;
use App\Http\Controllers\Dashboard\GroupServiceController;
use App\Http\Controllers\Dashboard\InsuranceController;
use App\Http\Controllers\Dashboard\AmbulanceController;
use App\Http\Controllers\Dashboard\LaboratoryEmployeeController;
use App\Http\Controllers\Dashboard\PatientController;
use App\Http\Controllers\Dashboard\PaymentController;
use App\Http\Controllers\Dashboard\RayEmployeeController;
use App\Http\Controllers\Dashboard\ReceiptController;
use App\Http\Controllers\Dashboard\SingleInvoiceController;
use App\Http\Controllers\Dashboard_Ray_Employee\InvoiceController as RayEmployeeInvoices;
use App\Http\Controllers\Dashboard_Laboratorie_Employee\InvoiceController as LaboratoryEmployeeInvoices;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

// Route::middleware('auth')->group(function () {
//     Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
//     Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
//     Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
// });

require __DIR__ . '/auth.php';



//dashboard
Route::get('/', function () {
    return view('welcome');
});

//user dashboard
Route::get('/dashboard/user', function () {
    return view('dashboard.user.dash2');
})->middleware(['auth', 'verified'])->name('dashboard.user');


//admin dashboard

Route::get('/dashboard/admin', function () {
    return view('dashboard.admin.dash2');
})->middleware(['auth:admin'])->name('dashboard.admin');



Route::middleware(['auth:admin,rayEmployee,laboratoryEmployee,patient,doctor'])->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

Route::middleware(['auth:admin'])->group(function () {
    Route::resource('Sections', SectionController::class);
    Route::patch('doctorActive/{id}',[DoctorController::class,'doctorActive'])->name('doctorActive');
    Route::resource('Doctors', DoctorController::class);

    Route::resource('SingleServices', SingleServiceController::class);
    Route::resource('GroupServices', GroupServiceController::class);
    Route::patch('insuranceActive/{id}',[InsuranceController::class,'insuranceActive'])->name('insuranceActive');
    Route::resource('Insurances', InsuranceController::class);
    Route::resource('Ambulances', AmbulanceController::class);
    Route::resource('Patients', PatientController::class);
    Route::resource('SingleInvoices', SingleInvoiceController::class);
    // Route::resource('GroupInvoices', SingleInvoiceController::class);
    Route::get('printReceiptBill/{id}', [ReceiptController::class,'PrintBill'])->name('printReceiptBill');
    Route::resource('Receipts', ReceiptController::class);
    Route::get('printPaymentBill/{id}', [PaymentController::class,'PrintBill'])->name('printPaymentBill');
    Route::resource('Payments', PaymentController::class);
    Route::resource('RayEmployees', RayEmployeeController::class);
    Route::get('AllRayEmployeeInvoices', [RayEmployeeInvoices::class,'AllInvoices']);
    Route::resource('LaboratoryEmployees', LaboratoryEmployeeController::class);
    Route::get('AllLaboratoryEmployeeInvoices',[ LaboratoryEmployeeInvoices::class,'AllInvoices']);
});



//website

Route::get('/google/redirect', [GoogleLoginController::class, 'redirectToGoogle'])->name('google.redirect');
Route::get('/google/callback', [GoogleLoginController::class, 'handleGoogleCallback'])->name('google.callback');

//
Route::get('/loginPage', function () {
    return view('dashboard.user.auth.loginPage');
});

app/Models/Receipt.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Receipt extends Model
{
    use HasFactory;
    protected $fillable=[
        'date',
        'patient_id',
        'amount',
        'description',
     ];

     public function patient(): BelongsTo
     {
         return $this->belongsTo(Patient::class);
     }
}

app/Http/Controllers/Dashboard/ReceiptController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Interfaces\Finances\ReceiptRepositoryInterface;
use Illuminate\Http\Request;

class ReceiptController extends Controller
{
    private $Receipts;

    public function __construct(ReceiptRepositoryInterface $Receipts)
    {
        $this->Receipts=$Receipts;
    }

    public function index()
    {
        return $this->Receipts->index();
    }

    public function create()
    {
        return $this->Receipts->create();
    }

    public function store(Request $request)
    {
        return $this->Receipts->store($request->input());
    }

    public function show($id)
    {
        return $this->Receipts->show($id);
    }

    public function edit($id)
    {
        return $this->Receipts->edit($id);
    }

    public function update(Request $request, $id)
    {
        return $this->Receipts->update($request->input(), $id);
    }

    public function destroy($id)
    {
        return $this->Receipts->destroy($id);
    }

    public function PrintBill(Request $request,$id)
    {
        return $this->Receipts->PrintBill($id);
    }
}

resources/views/dashboard/Finances/Receipts/add.blade.php
@extends('layouts.dashboard.master')

@section('title')
    Add Single Service Invoices
@endsection

@push('css')
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link href="https://cdn.datatables.net/2.0.4/css/dataTables.bootstrap4.css"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous">

    <style>
        body {
            background-color: #fff;
        }

        .nav li a {
            color: white !important;
        }

        #ServicesTable {
            display: none;
        }
    </style>
@endpush

@section('content')
    @include('layouts.dashboard.main-headerbar')

    <main class="main mt-5 pt-3">
        <section>
            <div class="container-fluid ">
                <div class="row ">
                    @include('layouts.dashboard.main-sidebar')
                    <div class="col-10 col-sm-10  col-md-10 col-lg-10 col-xl-10 pb-3 mt-1 ps-0">
                        <div class="container-fluid px-0">
                            <h5 class="text-light py-3 ps-2" style="background-color: rgb(16, 16, 17)"> Add Receipt Invoice
                            </h5>
                        </div>

                        <div class="container mt-3 py-2 ps-3">
                            <form method="POST" action="{{ route('Receipts.store') }}">
                                @csrf
                                    <div class="border border-1 p-3 mb-3 ps-4">
                                        <div class="row">
                                            <div class="col-lg-8">
                                                <div class="form-group mb-2">
                                                    <label for="name">Patient Name:</label>
                                                    <select class="form-select" aria-label="Default select example" id="patient_id"
                                                        name="patient_id">
                                                        <option selected>Open this select menu</option>
                                                        @foreach ($patients as $patient)
                                                            <option value="{{ $patient->id }}">{{ $patient->full_name }}</option>
                                                        @endforeach
                                                    </select>
                                                </div>
                                            </div>
                                            <div class="col-lg-8">
                                                <div class="form-group mb-2">
                                                    <label for="name">Date:</label>
                                                    <input type="date" id="date" class="form-control" placeholder="date"
                                                        name="date" required autofocus autocomplete="date">
                                                </div>
                                            </div>
                                            <div class="col-lg-8">
                                                <div class="form-group mb-2">
                                                    <label for="amount">amount:</label>
                                                    <input type="text" id="amount" class="form-control" placeholder="amount"
                                                        name="amount" required autofocus autocomplete="amount">
                                                </div>
                                            </div>
                                            <div class="col-lg-8">
                                                <div class="form-group mb-2">
                                                    <label for="description">description:</label>
                                                    <textarea type="text" id="description" class="form-control" placeholder="description"
                                                    name="description" autofocus autocomplete="description" rows="5">

                                                    </textarea>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    {{-- <div class="col-7 w-100 text-center">
                                        <button type="submit" class="btn btn-primary mb-2 w-75" >save</button>
                                    </div> --}}




                                    <button type="submit" class="btn btn-primary">Save</button>

                            </form>
                        </div>
                    </div>
                    {{-- @include('dashboard.Sections.add')
                    @foreach ($sections as $section)
                         @include('dashboard.Sections.edit')
                         @include('dashboard.Sections.delete')
                    @endforeach --}}

                </div>

            </div>
        </section>

    </main>
@endsection


@push('scripts')
    <script>

    </script>
@endpush

resources/views/dashboard/Finances/Receipts/delete.blade.php
{{-- delete section --}}
{{-- edit section --}}



<!-- Modal -->
<div class="modal fade" id="delete{{$Receipt->id}}" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel{{ $Receipt->id }}" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel{{ $Receipt->id }}">delete Receipt</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <form method="POST" action="{{ route('Receipts.destroy',[$Receipt->id]) }}">
            {{method_field('delete')}}

            {{ csrf_field() }}
            @csrf
        <div class="modal-body">

             <input type="hidden" name="id" value="{{$Receipt->id}}">
             <h5>Are You Sure You Want To Delete This Receipt?</h5>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-danger">Delete</button>
        </div>
    </form>
      </div>
    </div>
  </div>

resources/views/dashboard/Finances/Receipts/e.blade.php
<form method="POST" action="{{ route('Receipts.update', [$Receipt->id]) }}">
    {{ method_field('patch') }}

    {{ csrf_field() }}
    @csrf
    <div class="modal-body">

        <div class="form-row">
            <input type="hidden" name="id" value="{{ $Receipt->id }}">
            <div class="col-lg-7 w-75 mx-auto">
                <div class="form-group mb-2">
                    <label for="name">Data:</label>
                    <input type="date" id="date" class="form-control" placeholder="date"
                        name="date" required autofocus autocomplete="date" value="{{ $Receipt->date }}">
                </div>
            </div>
            <div class="col-lg-7 w-75 mx-auto">
                <div class="form-group mb-2">
                    <label for="amount">amount:</label>
                    <input type="text" id="amount" class="form-control" placeholder="amount"
                        name="amount" required autofocus autocomplete="amount"
                        value="{{ $Receipt->amount }}">
                </div>
            </div>
            <div class="col-lg-7 w-75 mx-auto">
                <div class="form-group mb-2">
                    <label for="description">description:</label>
                    <input type="text" id="description" class="form-control" placeholder="description"
                        name="description" autofocus autocomplete="description"
                        value="{{ $Receipt->description }}">
                </div>
            </div>
        </div>


        {{-- <div class="col-7 w-100 text-center">
            <button type="submit" class="btn btn-primary mb-2 w-75" >save</button>
        </div> --}}

    </div>

</div>
<div class="modal-footer">
<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
<button type="submit" class="btn btn-primary">Save</button>
</div>
</form>

resources/views/dashboard/Finances/Receipts/edit.blade.php
@extends('layouts.dashboard.master')

@section('title')
    Add Single Service Invoices
@endsection

@push('css')
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link href="https://cdn.datatables.net/2.0.4/css/dataTables.bootstrap4.css"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous">

    <style>
        body {
            background-color: #fff;
        }

        .nav li a {
            color: white !important;
        }

        #ServicesTable {
            display: none;
        }
    </style>
@endpush

@section('content')
    @include('layouts.dashboard.main-headerbar')

    <main class="main mt-5 pt-3">
        <section>
            <div class="container-fluid ">
                <div class="row ">
                    @include('layouts.dashboard.main-sidebar')
                    <div class="col-10 col-sm-10  col-md-10 col-lg-10 col-xl-10 pb-3 mt-1 ps-0">
                        <div class="container-fluid px-0">
                            <h5 class="text-light py-3 ps-2" style="background-color: rgb(16, 16, 17)"> Add Receipt Invoice
                            </h5>
                        </div>

                        <div class="container mt-3 py-2 ps-3">
                            <form method="POST" action="{{ route('Receipts.update', [$Receipt->id]) }}">
                                {{ method_field('patch') }}
                                {{ csrf_field() }}
                                @csrf
                                    <div class="border border-1 p-3 mb-3 ps-4">
                                        <div class="row">
                                            <div class="col-lg-8">
                                                <div class="form-group mb-2">
                                                    <label for="name">Patient Name:</label>
                                                    <select class="form-select" aria-label="Default select example" id="patient_id"
                                                        name="patient_id">
                                                        @foreach ($patients as $patient)
                                                        <option value="{{ $patient->id }}" {{$Receipt->patient->id==$patient->id}}? selected : ''>{{ $patient->full_name }}</option>
                                                        @endforeach

                                                    </select>
                                                </div>
                                            </div>
                                            <div class="col-lg-8">
                                                <div class="form-group mb-2">
                                                    <label for="name">Date:</label>
                                                    <input type="date" id="date" class="form-control" placeholder="date"
                                                        name="date" required autofocus autocomplete="date" value="{{ $Receipt->date }}">
                                                </div>
                                            </div>
                                            <div class="col-lg-8">
                                                <div class="form-group mb-2">
                                                    <label for="amount">amount:</label>
                                                    <input type="text" id="amount" class="form-control" placeholder="amount"
                                                        name="amount" required autofocus autocomplete="amount" value="{{ $Receipt->amount }}">
                                                </div>
                                            </div>
                                            <div class="col-lg-8">
                                                <div class="form-group mb-2">
                                                    <label for="description">description:</label>
                                                    <textarea type="text" id="description" class="form-control" placeholder="description"
                                                    name="description" autofocus autocomplete="description" rows="5">
                                                    {{ $Receipt->description }}
                                                    </textarea>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    {{-- <div class="col-7 w-100 text-center">
                                        <button type="submit" class="btn btn-primary mb-2 w-75" >save</button>
                                    </div> --}}




                                    <button type="submit" class="btn btn-primary">Save</button>

                            </form>
                        </div>
                    </div>
                    {{-- @include('dashboard.Sections.add')
                    @foreach ($sections as $section)
                         @include('dashboard.Sections.edit')
                         @include('dashboard.Sections.delete')
                    @endforeach --}}

                </div>

            </div>
        </section>

    </main>
@endsection


@push('scripts')
    <script>

    </script>
@endpush

resources/views/dashboard/Finances/Receipts/index.blade.php
@extends('layouts.dashboard.master')

@section('title')
  Receipts table
@endsection

@push('css')
<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
<link href="https://cdn.datatables.net/2.0.4/css/dataTables.bootstrap4.css" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous">

    <style>
        body {
            background-color: #fff;
        }
        .nav li a {
            color: white !important;
        }
    </style>
@endpush

@section('content')
        @include('layouts.dashboard.main-headerbar')

    <main class="main mt-5 pt-3">
        <section>
            <div class="container-fluid">
                <div class="row ">
                    @include('layouts.dashboard.main-sidebar')
                    <div class="col-10 col-sm-10  col-md-10 col-lg-10 col-xl-10 py-3 mt-3">
                        <button type="button" class="btn btn-success mb-3">
                            <a href="{{route('Receipts.create')}}">
                                Add Receipts
                            </a>
                          </button>

                        <table id="example" class="table table-striped table-bordered" style="width:100%">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Patient Name</th>
                                    <th>Amount</th>
                                    <th>Date</th>
                                    <th>Description</th>
                                    <th>Operation</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($Receipts as $Receipt)
                                <tr>
                                    <td>{{$Receipt->id}}</td>
                                    <td>{{$Receipt->patient->full_name}}</td>
                                    <td>{{$Receipt->amount}}</td>
                                    <td>{{$Receipt->date}}</td>

                                    <td>{{$Receipt->description}}</td>
                                    <td>
                                        <button type="button" class="btn btn-primary" ><a href="{{route('Receipts.edit',[$Receipt->id])}}"><i class="bi bi-pencil-fill"></i></a> </button>
                                        <button type="button" class="btn btn-danger"  data-toggle="modal" data-target="#delete{{$Receipt->id}}"> <i class="bi bi-trash3-fill"></i></button>
                                        <button type="button" class="btn btn-success" > <a href="{{route('Receipts.show',[$Receipt->id])}}" target="_blank"><i class="bi bi-printer-fill"></i></a></button>
                                    </td>
                                </tr>
                                @endforeach

                            </tbody>

                        </table>
                    </div>
                    {{-- @include('dashboard.Finances.Receipts.add') --}}
                    @foreach ($Receipts as $Receipt)
                         {{-- @include('dashboard.Finances.Receipts.edit') --}}
                         @include('dashboard.Finances.Receipts.delete')
                         {{-- @include('dashboard.Finances.Receipts.print') --}}
                    @endforeach

                </div>

            </div>
        </section>

    </main>
@endsection


@push('scripts')
<script defer src="https://code.jquery.com/jquery-3.7.1.js"></script>
    <script defer src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script defer src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script defer src="https://cdn.datatables.net/2.0.4/js/dataTables.js"></script>
    <script defer src="https://cdn.datatables.net/2.0.4/js/dataTables.bootstrap4.js"></script>
    <script>
$(document).ready(function() {
           new DataTable('#example');
        });
    </script>
@endpush

resources/views/dashboard/Finances/Receipts/print.blade.php
                <div class="row ">
                    {{-- @include('layouts.dashboard.main-sidebar') --}}
                    <div class="col py-3 mt-3">



                         <div style="text-align: center;">فاتورة سند قبض</div>



                            <br><br>
                            <table  style="border: 1px solid black;border-collapse: collapse">
                                <tr>
                                    <th style="border: 1px solid black;border-collapse: collapse">رقم الفاتورة</th>
                                    <th style="border: 1px solid black;border-collapse: collapse">السعر</th>
                                    <th style="border: 1px solid black;border-collapse: collapse">اسم المريض</th>
                                    <th style="border: 1px solid black;border-collapse: collapse">التاريخ</th>
                                </tr>

                                <tr>
                                    <td style="border: 1px solid black;border-collapse: collapse">{{ $result['id'] }}</td>
                                    <td style="border: 1px solid black;border-collapse: collapse">{{ $result['amount'] }}</td>
                                    <td style="border: 1px solid black;border-collapse: collapse">{{ $result['patient_name'] }}</td>
                                    <td style="border: 1px solid black;border-collapse: collapse">{{ $result['date'] }}</td>

                                </tr>



                            </table>



                            </div>
                    </div>
                </div>

resources/views/dashboard/Finances/Receipts/show.blade.php
@extends('layouts.dashboard.master')

@section('title')
  Receipts table
@endsection

@push('css')
<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
<link href="https://cdn.datatables.net/2.0.4/css/dataTables.bootstrap4.css" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous">

    <style>
        body {
            background-color: #fff;
        }
        .nav li a {
            color: white !important;
        }
    </style>
@endpush
@section('content')
        @include('layouts.dashboard.main-headerbar')

    <main class="main mt-5 pt-3">
        <section>
            <div class="container-fluid">
                <div class="row ">
                    {{-- @include('layouts.dashboard.main-sidebar') --}}
                    <div class="col-10 col-sm-10  col-md-10 col-lg-10 col-xl-10 py-3 mt-3">



                            <div style="text-align: center;">فاتورة سند قبض</div>



                            <br><br>
                            <table class="table  table-responsive table-striped table-bordered">
                                <tr>
                                    <th>رقم الفاتورة</th>
                                    <th>السعر</th>
                                    <th>اسم المريض</th>
                                    <th>التاريخ</th>
                                </tr>

                                <tr>
                                    <td>{{ $Receipt['id'] }}</td>
                                    <td>{{ $Receipt['amount'] }}</td>
                                    <td>{{ $Receipt['patient']['full_name'] }}</td>
                                    <td>{{ $Receipt['date'] }}</td>

                                </tr>



                            </table>



                            <button type="submit" class="btn btn-primary"><a href="{{route('printReceiptBill',[$Receipt['id']])}}">Print</a></button>
                            </div>
                    </div>
                </div>

            </div>
        </section>

    </main>
@endsection