routes/web.php
<?php

use App\Http\Controllers\Auth\GoogleLoginController;
use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Dashboard\DoctorController;
use App\Http\Controllers\Dashboard\SectionController;
use App\Http\Controllers\Dashboard\SingleServiceController;
use App\Http\Controllers\Dashboard\GroupServiceController;
use App\Http\Controllers\Dashboard\InsuranceController;
use App\Http\Controllers\Dashboard\AmbulanceController;
use App\Http\Controllers\Dashboard\LaboratoryEmployeeController;
use App\Http\Controllers\Dashboard\PatientController;
use App\Http\Controllers\Dashboard\PaymentController;
use App\Http\Controllers\Dashboard\RayEmployeeController;
use App\Http\Controllers\Dashboard\ReceiptController;
use App\Http\Controllers\Dashboard\SingleInvoiceController;
use App\Http\Controllers\Dashboard_Ray_Employee\InvoiceController as RayEmployeeInvoices;
use App\Http\Controllers\Dashboard_Laboratorie_Employee\InvoiceController as LaboratoryEmployeeInvoices;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

// Route::middleware('auth')->group(function () {
//     Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
//     Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
//     Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
// });

require __DIR__ . '/auth.php';



//dashboard
Route::get('/', function () {
    return view('welcome');
});

//user dashboard
Route::get('/dashboard/user', function () {
    return view('dashboard.user.dash2');
})->middleware(['auth', 'verified'])->name('dashboard.user');


//admin dashboard

Route::get('/dashboard/admin', function () {
    return view('dashboard.admin.dash2');
})->middleware(['auth:admin'])->name('dashboard.admin');



Route::middleware(['auth:admin,rayEmployee,laboratoryEmployee,patient,doctor'])->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

Route::middleware(['auth:admin'])->group(function () {
    Route::resource('Sections', SectionController::class);
    Route::patch('doctorActive/{id}',[DoctorController::class,'doctorActive'])->name('doctorActive');
    Route::resource('Doctors', DoctorController::class);

    Route::resource('SingleServices', SingleServiceController::class);
    Route::resource('GroupServices', GroupServiceController::class);
    Route::patch('insuranceActive/{id}',[InsuranceController::class,'insuranceActive'])->name('insuranceActive');
    Route::resource('Insurances', InsuranceController::class);
    Route::resource('Ambulances', AmbulanceController::class);
    Route::resource('Patients', PatientController::class);
    Route::resource('SingleInvoices', SingleInvoiceController::class);
    // Route::resource('GroupInvoices', SingleInvoiceController::class);
    Route::get('printReceiptBill/{id}', [ReceiptController::class,'PrintBill'])->name('printReceiptBill');
    Route::resource('Receipts', ReceiptController::class);
    Route::get('printPaymentBill/{id}', [PaymentController::class,'PrintBill'])->name('printPaymentBill');
    Route::resource('Payments', PaymentController::class);
    Route::resource('RayEmployees', RayEmployeeController::class);
    Route::get('AllRayEmployeeInvoices', [RayEmployeeInvoices::class,'AllInvoices']);
    Route::resource('LaboratoryEmployees', LaboratoryEmployeeController::class);
    Route::get('AllLaboratoryEmployeeInvoices',[ LaboratoryEmployeeInvoices::class,'AllInvoices']);
});



//website

Route::get('/google/redirect', [GoogleLoginController::class, 'redirectToGoogle'])->name('google.redirect');
Route::get('/google/callback', [GoogleLoginController::class, 'handleGoogleCallback'])->name('google.callback');

//
Route::get('/loginPage', function () {
    return view('dashboard.user.auth.loginPage');
});

app/Models/Section.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Section extends Model
{
    use HasFactory;

    protected $fillable=[
       'name',
       'description'
    ];

    public function doctors(): HasMany
    {
        return $this->hasMany(Doctor::class);
    }
}

app/Http/Controllers/Dashboard/AmbulanceController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Interfaces\Ambulances\AmbulanceRepositoryInterface;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class AmbulanceController extends Controller
{
    private $Ambulance;

    public function __construct(AmbulanceRepositoryInterface $Ambulance)
    {
        $this->Ambulance=$Ambulance;
    }

    public function index()
    {
        return $this->Ambulance->index();
    }

    public function create()
    {
        return $this->Ambulance->create();
    }

    public function store(Request $request)
    {
        return $this->Ambulance->store($request->input());
    }

    public function edit($id)
    {
        return $this->Ambulance->edit($id);
    }

    public function update(Request $request, $id)
    {
        return $this->Ambulance->update($request->input(), $id);
    }

    public function destroy($id)
    {
        return $this->Ambulance->destroy($id);
    }
}

app/Http/Controllers/Dashboard/DashboardController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
     public function index()
     {
        return view('welcome');
     }
}

app/Http/Controllers/Dashboard/DoctorController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Interfaces\Doctors\DoctorRepositoryInterface;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class DoctorController extends Controller
{
    private $Doctors;

    public function __construct(DoctorRepositoryInterface $Doctors)
    {
        $this->Doctors=$Doctors;
    }

    public function index()
    {
        return $this->Doctors->index();
    }

    public function store(Request $request)
    {
        return $this->Doctors->store($request);
    }


    public function edit($id)
    {
        return $this->Doctors->edit($id);
    }

    public function update(Request $request, $id)
    {
        return $this->Doctors->update($request,$id);
    }

    public function doctorActive(Request $request, $id)
    {
        return $this->Doctors->doctorActive($request->input(),$id);
    }

    public function destroy($id)
    {
        return $this->Doctors->destroy($id);
    }
}

app/Http/Controllers/Dashboard/GroupServiceController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Interfaces\Services\GroupServiceRepositoryInterface;
use Illuminate\Http\Request;

class GroupServiceController extends Controller
{
    private $GroupService;

    public function __construct(GroupServiceRepositoryInterface $GroupService)
    {
        $this->GroupService=$GroupService;
    }

    public function index()
    {
        return $this->GroupService->index();
    }

    public function create()
    {
        return $this->GroupService->create();
    }

    public function store(Request $request)
    {
        return $this->GroupService->store($request->input());
    }


    public function update(Request $request, $id)
    {
        return $this->GroupService->update($request->input(), $id);
    }

    public function destroy($id)
    {
        return $this->GroupService->destroy($id);
    }
}

app/Http/Controllers/Dashboard/InsuranceController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Interfaces\Insurances\InsuranceRepositoryInterface;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class InsuranceController extends Controller
{
    private $Insurance;

    public function __construct(InsuranceRepositoryInterface $Insurance)
    {
        $this->Insurance=$Insurance;
    }

    public function index()
    {
        return $this->Insurance->index();
    }

    public function create()
    {
        return $this->Insurance->create();
    }

    public function store(Request $request)
    {
        return $this->Insurance->store($request->input());
    }

    public function insuranceActive(Request $request, $id)
    {
        return $this->Insurance->insuranceActive($request->input(),$id);
    }

    public function update(Request $request, $id)
    {
        return $this->Insurance->update($request->input(), $id);
    }

    public function destroy($id)
    {
        return $this->Insurance->destroy($id);
    }
}

app/Http/Controllers/Dashboard/LaboratoryEmployeeController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Interfaces\LaboratoryEmployee\LaboratoryEmployeeRepositoryInterface;
use Illuminate\Http\Request;

class LaboratoryEmployeeController extends Controller
{
    private $LaboratoryEmployee;

    public function __construct(LaboratoryEmployeeRepositoryInterface $LaboratoryEmployee)
    {
        $this->LaboratoryEmployee=$LaboratoryEmployee;
    }

    public function index()
    {
        return $this->LaboratoryEmployee->index();
    }

    public function store(Request $request)
    {
        return $this->LaboratoryEmployee->store($request->all());
    }

    public function update(Request $request, $id)
    {
        return $this->LaboratoryEmployee->update($request->all(), $id);
    }

    public function destroy($id)
    {
        return $this->LaboratoryEmployee->destroy($id);
    }
}

app/Http/Controllers/Dashboard/PatientController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Interfaces\Patients\PatientRepositoryInterface;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class PatientController extends Controller
{
    private $Patient;

    public function __construct(PatientRepositoryInterface $Patient)
    {
        $this->Patient=$Patient;
    }

    public function index()
    {
        return $this->Patient->index();
    }

    public function create()
    {
        return $this->Patient->create();
    }

    public function store(Request $request)
    {
        return $this->Patient->store($request->input());
    }

    public function show($id)
    {
        return $this->Patient->show($id);
    }

    public function edit($id)
    {
        return $this->Patient->edit($id);
    }

    public function update(Request $request, $id)
    {
        return $this->Patient->update( $request->input(), $id);
    }

    public function destroy($id)
    {
        return $this->Patient->destroy($id);
    }
}

app/Http/Controllers/Dashboard/PaymentController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Interfaces\Finances\PaymentRepositoryInterface;
use Illuminate\Http\Request;

class PaymentController extends Controller
{
    private $Payments;

    public function __construct(PaymentRepositoryInterface $Payments)
    {
        $this->Payments=$Payments;
    }

    public function index()
    {
        return $this->Payments->index();
    }

    public function create()
    {
        return $this->Payments->create();
    }

    public function store(Request $request)
    {
        return $this->Payments->store($request->input());
    }

    public function edit($id)
    {
        return $this->Payments->edit($id);
    }

    public function update(Request $request, $id)
    {
        return $this->Payments->update($request->input(), $id);
    }

    public function destroy($id)
    {
        return $this->Payments->destroy($id);
    }

    public function PrintBill($id)
    {
        return $this->Payments->PrintBill($id);
    }
}

app/Http/Controllers/Dashboard/RayEmployeeController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Interfaces\RayEmployees\RayEmployeeRepositoryInterface;
use Illuminate\Http\Request;

class RayEmployeeController extends Controller
{
    private $RayEmployee;

    public function __construct(RayEmployeeRepositoryInterface $RayEmployee)
    {
        $this->RayEmployee=$RayEmployee;
    }

    public function index()
    {
        return $this->RayEmployee->index();
    }

    public function store(Request $request)
    {
        return $this->RayEmployee->store($request->input());
    }

    public function update(Request $request, $id)
    {
        return $this->RayEmployee->update($request->all(), $id);
    }

    public function destroy($id)
    {
        return $this->RayEmployee->destroy($id);
    }
}

app/Http/Controllers/Dashboard/ReceiptController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Interfaces\Finances\ReceiptRepositoryInterface;
use Illuminate\Http\Request;

class ReceiptController extends Controller
{
    private $Receipts;

    public function __construct(ReceiptRepositoryInterface $Receipts)
    {
        $this->Receipts=$Receipts;
    }

    public function index()
    {
        return $this->Receipts->index();
    }

    public function create()
    {
        return $this->Receipts->create();
    }

    public function store(Request $request)
    {
        return $this->Receipts->store($request->input());
    }

    public function show($id)
    {
        return $this->Receipts->show($id);
    }

    public function edit($id)
    {
        return $this->Receipts->edit($id);
    }

    public function update(Request $request, $id)
    {
        return $this->Receipts->update($request->input(), $id);
    }

    public function destroy($id)
    {
        return $this->Receipts->destroy($id);
    }

    public function PrintBill(Request $request,$id)
    {
        return $this->Receipts->PrintBill($id);
    }
}

app/Http/Controllers/Dashboard/SectionController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Interfaces\Sections\SectionRepositoryInterface;
use Illuminate\Http\Request;

class SectionController extends Controller
{
    private $Sections;

    public function __construct(SectionRepositoryInterface $Sections)
    {
        $this->Sections=$Sections;
    }

    public function index()
    {
       return $this->Sections->index();
    }

    public function create()
    {
        return view('dashboard.Sections.add');
    }

    public function store(Request $request)
    {
        return $this->Sections->store($request->input());
    }

    public function show($id)
    {
        return $this->Sections->show($id);
    }

    public function edit($id)
    {
        return view('dashboard.Sections.edit',compact('id'));
    }

    public function update(Request $request, $id)
    {
        return $this->Sections->update($request->input(),$id);
    }

    public function destroy($id)
    {
        return $this->Sections->destroy($id);
    }

}

app/Http/Controllers/Dashboard/SingleInvoiceController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;

use App\Interfaces\Invoices\SingleInvoiceRepositoryInterface;
use Illuminate\Http\Request;

class SingleInvoiceController extends Controller
{
    private $SingleInvoice;

    public function __construct(SingleInvoiceRepositoryInterface $SingleInvoice)
    {
        $this->SingleInvoice=$SingleInvoice;
    }

    public function index()
    {
        return $this->SingleInvoice->index();
    }

    public function create()
    {
        return $this->SingleInvoice->create();
    }


    public function store(Request $request)
    {
        return $this->SingleInvoice->store($request->input());
    }

    public function edit($id)
    {
        return $this->SingleInvoice->edit($id);
    }

    public function update(Request $request, $id)
    {
        return $this->SingleInvoice->update($request->input(), $id);
    }

    public function destroy($id)
    {
        return $this->SingleInvoice->destroy($id);
    }
}

app/Http/Controllers/Dashboard/SingleServiceController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Interfaces\Services\SingleServiceRepositoryInterface;
use Illuminate\Http\Request;

class SingleServiceController extends Controller
{
    private $SingleService;

    public function __construct(SingleServiceRepositoryInterface $SingleService)
    {
        $this->SingleService=$SingleService;
    }

    public function index()
    {
        return $this->SingleService->index();
    }

    public function create()
    {
        return $this->SingleService->create();
    }

    public function store(Request $request)
    {
        return $this->SingleService->store($request->input());
    }

    public function update(Request $request, $id)
    {
        return $this->SingleService->update($request->input(), $id);
    }

    public function destroy($id)
    {
        return $this->SingleService->destroy($id);
    }
}

resources/views/dashboard/Sections/add.blade.php
<!-- Modal -->
<div class="modal fade" id="add" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Add Section</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <form method="POST" action="{{ route('Sections.store') }}">
            @csrf
        <div class="modal-body">

                <div class="form-row">
                    <div class="col-lg-7 w-75 mx-auto">
                        <div class="form-group mb-2">
                            <label for="name">Name:</label>
                          <input type="text" id="name" class="form-control"  placeholder="name"
                          type="text" name="name"  required autofocus autocomplete="name"
                          >
                        </div>
                    </div>
                    <div class="col-lg-7 w-75 mx-auto">
                        <div class="form-group mb-2">
                            <label for="description">Description:</label>
                          <input type="text" id="description" class="form-control"  placeholder="description"
                          type="text" name="description"  required autofocus autocomplete="description"
                          >
                        </div>
                    </div>
                    {{-- <div class="col-7 w-100 text-center">
                        <button type="submit" class="btn btn-primary mb-2 w-75" >save</button>
                    </div> --}}

                </div>

                </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary">Save</button>
        </div>
    </form>
      </div>
    </div>
  </div>

resources/views/dashboard/Sections/delete.blade.php
{{-- edit section --}}



<!-- Modal -->
<div class="modal fade" id="delete{{$section->id}}" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel{{ $section->id }}" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel{{ $section->id }}">delete Section</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <form method="POST" action="{{ route('Sections.destroy',[$section->id]) }}">
            {{method_field('delete')}}

            {{ csrf_field() }}
            @csrf
        <div class="modal-body">

             <input type="hidden" name="id" value="{{$section->id}}">
             <h5>Are You Sure You Want To Delete This Section?</h5>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-danger">Delete</button>
        </div>
    </form>
      </div>
    </div>
  </div>

resources/views/dashboard/Sections/edit.blade.php
{{-- edit section --}}



<!-- Modal -->
<div class="modal fade" id="edit{{$section->id}}" tabindex="-1" role="dialog" aria-labelledby="editModalLabel{{ $section->id }}" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="editModalLabel{{ $section->id }}">update Section</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <form method="POST" action="{{ route('Sections.update',[$section->id]) }}">
            {{method_field('patch')}}

            {{ csrf_field() }}
            @csrf
        <div class="modal-body">

                <div class="form-row">
                    <div class="col-lg-7 w-75 mx-auto">
                        <input type="hidden" name="id" value="{{$section->id}}">
                        <div class="form-group mb-2">
                            <label for="name">Name:</label>
                            <input type="text" id="name" class="form-control"  placeholder="name"
                            type="text" name="name" value="{{$section->name}}" required autofocus autocomplete="name"
                            >
                          </div>
                    </div>
                    <div class="col-lg-7 w-75 mx-auto">
                        <div class="form-group mb-2">
                            <label for="description">Description:</label>
                          <input type="text" id="description" class="form-control"  placeholder="description"
                          type="text" name="description" value="{{$section->description}}" required autofocus autocomplete="description"
                          >
                        </div>
                    </div>
                    {{-- <div class="col-7 w-100 text-center">
                        <button type="submit" class="btn btn-primary mb-2 w-75" >save</button>
                    </div> --}}

                </div>

                </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary">Save</button>
        </div>
    </form>
      </div>
    </div>
  </div>

resources/views/dashboard/Sections/index.blade.php
@extends('layouts.dashboard.master')

@section('title')
    Sections table
@endsection

@push('css')
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link href="https://cdn.datatables.net/2.0.4/css/dataTables.bootstrap4.css"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous">

    <style>
        body {
            background-color: #fff;
        }

        .nav li a {
            color: white !important;
        }
    </style>
@endpush

@section('content')
    @include('layouts.dashboard.main-headerbar')

    <main class="main mt-5 pt-3">
        <section>
            <div class="container-fluid">
                <div class="row in-table" data="1">
                    @include('layouts.dashboard.main-sidebar')
                    <div class="col-10 col-sm-10  col-md-10 col-lg-10 col-xl-10 py-3 mt-3" id="in-table">
                        <button type="button" class="btn btn-success mb-3" data-toggle="modal" data-target="#add">
                            Add Section
                        </button>

                        <table id="example" class="table table-striped table-bordered" style="width:100%">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Name</th>
                                    <th>Description</th>
                                    <th>Cteate date</th>
                                    <th>OPrations</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($sections as $section)
                                    <tr>
                                        <td>{{ $section->id }}</td>
                                        <td><a href="{{ route('Sections.show', [$section->id]) }}">{{ $section->name }}</a>
                                        </td>
                                        <td>{!! Str::words($section->description, 10, '....') !!}</td>
                                        <td>{{ $section->created_at->diffForHumans() }}</td>
                                        <td>
                                            <button type="button" class="btn btn-primary" data-toggle="modal"
                                                data-target="#edit{{ $section->id }}"> <i
                                                    class="bi bi-pencil-fill"></i></button>
                                            <button type="button" class="btn btn-danger" data-toggle="modal"
                                                data-target="#delete{{ $section->id }}"> <i
                                                    class="bi bi-trash3-fill"></i></button>
                                        </td>
                                    </tr>
                                @endforeach

                            </tbody>

                        </table>
                    </div>
                    @include('dashboard.Sections.add')
                    @foreach ($sections as $section)
                        @include('dashboard.Sections.edit')
                        @include('dashboard.Sections.delete')
                    @endforeach

                </div>

            </div>
        </section>

    </main>
@endsection


@push('scripts')
    <script defer src="https://code.jquery.com/jquery-3.7.1.js"></script>
    <script defer src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script defer src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script defer src="https://cdn.datatables.net/2.0.4/js/dataTables.js"></script>
    <script defer src="https://cdn.datatables.net/2.0.4/js/dataTables.bootstrap4.js"></script>
    <script>
        $(document).ready(function() {
            new DataTable('#example');
        });
        // $('.in-table').click(function() {
        //     var d = $(this).attr('data');
        //     console.log(d);
        //     // const gridElement = document.getElementById('in-table');

        //     const columnElement = document.querySelector('.in-table .col:nth-child(1)');

        //     const columnClasses = $('.in-table').attr('class').split(' ');
        //     //   $('#divId').attr('class').split(/\s+/);

        //     let columnSize = '';

        //     // Loop through each class and check for a class starting with 'col-'
        //     $.each(columnClasses, function(index, className) {
        //         if (className.startsWith('col-')) {
        //             columnSize = className;
        //             return false;
        //         }
        //     });

        //     console.log('Column size:', columnSize);
        // });
    </script>
@endpush