routes/web.php
<?php

use App\Http\Controllers\Auth\GoogleLoginController;
use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Dashboard\DoctorController;
use App\Http\Controllers\Dashboard\SectionController;
use App\Http\Controllers\Dashboard\SingleServiceController;
use App\Http\Controllers\Dashboard\GroupServiceController;
use App\Http\Controllers\Dashboard\InsuranceController;
use App\Http\Controllers\Dashboard\AmbulanceController;
use App\Http\Controllers\Dashboard\LaboratoryEmployeeController;
use App\Http\Controllers\Dashboard\PatientController;
use App\Http\Controllers\Dashboard\PaymentController;
use App\Http\Controllers\Dashboard\RayEmployeeController;
use App\Http\Controllers\Dashboard\ReceiptController;
use App\Http\Controllers\Dashboard\SingleInvoiceController;
use App\Http\Controllers\Dashboard_Ray_Employee\InvoiceController as RayEmployeeInvoices;
use App\Http\Controllers\Dashboard_Laboratorie_Employee\InvoiceController as LaboratoryEmployeeInvoices;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

// Route::middleware('auth')->group(function () {
//     Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
//     Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
//     Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
// });

require __DIR__ . '/auth.php';



//dashboard
Route::get('/', function () {
    return view('welcome');
});

//user dashboard
Route::get('/dashboard/user', function () {
    return view('dashboard.user.dash2');
})->middleware(['auth', 'verified'])->name('dashboard.user');


//admin dashboard

Route::get('/dashboard/admin', function () {
    return view('dashboard.admin.dash2');
})->middleware(['auth:admin'])->name('dashboard.admin');



Route::middleware(['auth:admin,rayEmployee,laboratoryEmployee,patient,doctor'])->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

Route::middleware(['auth:admin'])->group(function () {
    Route::resource('Sections', SectionController::class);
    Route::patch('doctorActive/{id}',[DoctorController::class,'doctorActive'])->name('doctorActive');
    Route::resource('Doctors', DoctorController::class);

    Route::resource('SingleServices', SingleServiceController::class);
    Route::resource('GroupServices', GroupServiceController::class);
    Route::patch('insuranceActive/{id}',[InsuranceController::class,'insuranceActive'])->name('insuranceActive');
    Route::resource('Insurances', InsuranceController::class);
    Route::resource('Ambulances', AmbulanceController::class);
    Route::resource('Patients', PatientController::class);
    Route::resource('SingleInvoices', SingleInvoiceController::class);
    // Route::resource('GroupInvoices', SingleInvoiceController::class);
    Route::get('printReceiptBill/{id}', [ReceiptController::class,'PrintBill'])->name('printReceiptBill');
    Route::resource('Receipts', ReceiptController::class);
    Route::get('printPaymentBill/{id}', [PaymentController::class,'PrintBill'])->name('printPaymentBill');
    Route::resource('Payments', PaymentController::class);
    Route::resource('RayEmployees', RayEmployeeController::class);
    Route::get('AllRayEmployeeInvoices', [RayEmployeeInvoices::class,'AllInvoices']);
    Route::resource('LaboratoryEmployees', LaboratoryEmployeeController::class);
    Route::get('AllLaboratoryEmployeeInvoices',[ LaboratoryEmployeeInvoices::class,'AllInvoices']);
});



//website

Route::get('/google/redirect', [GoogleLoginController::class, 'redirectToGoogle'])->name('google.redirect');
Route::get('/google/callback', [GoogleLoginController::class, 'handleGoogleCallback'])->name('google.callback');

//
Route::get('/loginPage', function () {
    return view('dashboard.user.auth.loginPage');
});

app/Models/Invoice.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Invoice extends Model
{
    use HasFactory;
    protected $fillable=[
        'invoice_date',
        'invoice_type',
        'patient_id',
        'doctor_id',
        'section_id',
        'service_id',
        'group_id',
        'price',
        'discount_value',
        'tax_rate',
        'tax_value',
        'total_with_rate',
        'type',
        'invoice_status',
     ];

     public function group(): BelongsTo
    {
        return $this->belongsTo(Group::class);
    }

     public function patient(): BelongsTo
    {
        return $this->belongsTo(Patient::class);
    }

    public function doctor(): BelongsTo
    {
        return $this->belongsTo(Doctor::class);
    }

    public function section(): BelongsTo
    {
        return $this->belongsTo(Section::class);
    }

    public function service(): BelongsTo
    {
        return $this->belongsTo(SingleService::class);
    }

}

app/Http/Controllers/Dashboard_Laboratorie_Employee/InvoiceController.php
<?php

namespace App\Http\Controllers\Dashboard_Laboratorie_Employee;

use App\Http\Controllers\Controller;
use App\Interfaces\Dashboard_Laboratorie_Employee\InvoiceRepositoryInterface;
use Illuminate\Http\Request;

class InvoiceController extends Controller
{
    private $Invoice;

    public function __construct(InvoiceRepositoryInterface $Invoice)
    {
        $this->Invoice=$Invoice;
    }

     public function AllInvoices()
     {
         return $this->Invoice->AllInvoices();
     }

    public function index()
    {
        return $this->Invoice->index();
    }

    public function completedInvoices()
    {
        return $this->Invoice->completedInvoices();
    }

    public function viewLabs($id)
    {
        return $this->Invoice->viewLabs($id);
    }


    public function update(Request $request, $id)
    {
        return $this->Invoice->update($request, $id);
    }

    public function destroy($id)
    {
        return $this->Invoice->destroy( $id);
    }
}

app/Http/Controllers/Dashboard_Ray_Employee/InvoiceController.php
<?php

namespace App\Http\Controllers\Dashboard_Ray_Employee;

use App\Http\Controllers\Controller;
use App\Interfaces\Dashboard_Ray_Employee\InvoiceRepositoryInterface;
use Illuminate\Http\Request;

class InvoiceController extends Controller
{
    private $Invoice;

    public function __construct(InvoiceRepositoryInterface $Invoice)
    {
        $this->Invoice=$Invoice;
    }

    public function AllInvoices()
    {
        return $this->Invoice->AllInvoices();
    }

    public function index()
    {
        return $this->Invoice->index();
    }

    public function completedInvoices()
    {
        return $this->Invoice->completedInvoices();
    }

    public function viewRays($id)
    {
        return $this->Invoice->viewRays($id);
    }

    public function update(Request $request, $id)
    {
        return $this->Invoice->update($request, $id);
    }

    public function destroy($id)
    {
        return $this->Invoice->destroy( $id);
    }
}

app/Http/Controllers/DoctorDashboard/InvoiceController.php
<?php

namespace App\Http\Controllers\DoctorDashboard;

use App\Http\Controllers\Controller;
use App\Interfaces\DoctorDashboard\InvoiceRepositoryInterface;
use Illuminate\Http\Request;

class InvoiceController extends Controller
{
    private $Invoice;

    public function __construct(InvoiceRepositoryInterface $Invoice)
    {
        $this->Invoice=$Invoice;
    }

    public function index()
    {
        return $this->Invoice->index();
    }

    public function reviewInvoices()
    {
        return $this->Invoice->reviewInvoices();
    }

    public function completedInvoices()
    {
        return $this->Invoice->completedInvoices();
    }

    public function show($id)
    {
        return $this->Invoice->show($id);
    }

}

resources/views/dashboard/Invoices/GroupInvoices/add.blade.php
@extends('layouts.dashboard.master')

@section('title')
    Add Single Service Invoices
@endsection

@push('css')
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link href="https://cdn.datatables.net/2.0.4/css/dataTables.bootstrap4.css"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous">

    <style>
        body {
            background-color: #fff;
        }

        .nav li a {
            color: white !important;
        }

        #ServicesTable {
            display: none;
        }
    </style>
@endpush

@section('content')
    @include('layouts.dashboard.main-headerbar')

    <main class="main mt-5 pt-3">
        <section>
            <div class="container-fluid ">
                <div class="row ">
                    @include('layouts.dashboard.main-sidebar')
                    <div class="col-10 col-sm-10  col-md-10 col-lg-10 col-xl-10 pb-3 mt-1 ps-0">
                        <div class="container-fluid px-0">
                            <h5 class="text-light py-3 ps-2" style="background-color: rgb(16, 16, 17)"> Add Service Invoices
                            </h5>
                        </div>

                        <div class="container mt-3 py-2 ps-3">
                            <form method="POST" action="{{ route('SingleInvoices.store') }}">
                                @csrf
                                <div class="row">
                                    <div class="col-lg-3">
                                        <div class="form-group mb-2">
                                            <label for="name">Patient Name:</label>
                                            <select class="form-select" aria-label="Default select example" id="patient_id"
                                                name="patient_id">
                                                <option selected>Open this select menu</option>
                                                @foreach ($patients as $patient)
                                                    <option value="{{ $patient->id }}">{{ $patient->full_name }}</option>
                                                @endforeach
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-lg-3">
                                        <div class="form-group mb-2">
                                            <label for="name">Doctor Name:</label>
                                            <select class="form-select doctor" aria-label="Default select example"
                                                id="doctor_id" name="doctor_id">
                                                <option selected>Open this select menu</option>
                                                @foreach ($doctors as $doctor)
                                                    <option value="{{ $doctor->id }}"
                                                        section="{{ $doctor->section->name }}">{{ $doctor->full_name }}
                                                    </option>
                                                @endforeach
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-lg-3">
                                        <div class="form-group mb-2">
                                            <label for="name">section:</label>
                                            <input type="text" id="section" class="form-control section"
                                                placeholder="section" name="section_id" autofocus>
                                        </div>
                                    </div>
                                    <div class="col-lg-3">
                                        <div class="form-group mb-2">
                                            <label for="name">invoice date:</label>
                                            <input type="date" id="invoice_date" class="form-control"
                                                placeholder="invoice date" name="invoice_date" autofocus>
                                        </div>
                                    </div>
                                    <div class="col-lg-6">
                                        <div class="form-group mb-2">
                                            <label for="name">Invoice Type:</label>
                                            <select class="form-select" aria-label="Default select example"
                                                id="invoice_type" name="invoice_type">
                                                <option selected>Open this select menu</option>
                                                <option value="single">single</option>
                                                <option value="group">group</option>

                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-lg-6">
                                        <div class="form-group mb-2">
                                            <label for="name"> Type:</label>
                                            <select class="form-select" aria-label="Default select example" id="type"
                                                name="type">
                                                <option selected>Open this select menu</option>
                                                <option value="1">آجل</option>
                                                <option value="2">نقدي</option>

                                            </select>
                                        </div>
                                    </div>
                                    <div class=" row border border-1 mt-1 mx-3 mb-2 py-2">
                                        <div class="col-lg-4">
                                            <div class="form-group mb-2">
                                                <label for="name">Service:</label>
                                                <select class="form-select service" aria-label="Default select example"
                                                    id="service_id" name="service_id">
                                                    <option selected disabled>Open this select menu</option>
                                                    @foreach ($services as $service)
                                                        <option value="{{ $service->id }}" price="{{ $service->price }}"
                                                            service-data="{{$service}}" >
                                                            {{ $service->name }}</option>
                                                    @endforeach
                                                </select>
                                            </div>
                                        </div>
                                        <div class="col-lg-4">
                                            <div class="form-group mb-2">
                                                <label for="price">Price:</label>
                                                <input type="text" id="price" class="form-control price"
                                                    placeholder="price" name="price" required autofocus
                                                    autocomplete="price">
                                            </div>
                                        </div>
                                        <div class="col-lg-4">
                                            <div class="form-group mb-2">
                                                <label for="email">discount value:</label>
                                                <input type="text" id="discount_value" class="form-control discount"
                                                    placeholder="discount value" name="discount_value" required autofocus
                                                    autocomplete="discount_value">
                                            </div>
                                        </div>
                                        <div class="col-lg-4">
                                            <div class="form-group mb-2">
                                                <label for="tax_rate">tax rate:</label>
                                                <input type="text" id="tax_rate" class="form-control tax-rate"
                                                    placeholder="tax rate" name="tax_rate" required autofocus
                                                    autocomplete="tax_rate">
                                            </div>
                                        </div>
                                        <div class="col-lg-4">
                                            <div class="form-group mb-2">
                                                <label for="tax_rate">total with tax:</label>
                                                <input type="text" id="tax_value" class="form-control tax-value"
                                                    placeholder="total tax" name="tax_value" required autofocus
                                                    autocomplete="tax_value">
                                            </div>
                                        </div>
                                        <div class="col-lg-4">
                                            <div class="form-group mb-2">
                                                <label for="tax_rate">Total:</label>
                                                <input type="text" id="total" class="form-control total"
                                                    placeholder="total" name="total" required autofocus
                                                    autocomplete="total">
                                            </div>
                                        </div>

                                    </div>





                                    {{-- <div class="col-7 w-100 text-center">
                                    <button type="submit" class="btn btn-primary mb-2 w-75" >save</button>
                                </div> --}}

                                </div>

                                <button type="submit" class="btn btn-primary">Save</button>
                            </form>
                        </div>
                    </div>
                    {{-- @include('dashboard.Sections.add')
                    @foreach ($sections as $section)
                         @include('dashboard.Sections.edit')
                         @include('dashboard.Sections.delete')
                    @endforeach --}}

                </div>

            </div>
        </section>

    </main>
@endsection


@push('scripts')
    <script>
        $(document).ready(function() {
            $('.doctor').on("change", function() {
                let section = $('option:selected', this).attr('section');
                console.log(section);
                $('.section').val(section);
            });

            $('.service').on("change", function() {
                let price = $('option:selected', this).attr('price');
                const serviceed = $('option:selected', this).attr('service-data');
                console.log(price);
                var name=serviceed.name;
                console.log(name);
                $('.price').val(price);
                $('.total').val(price);





            });





        });
    </script>
@endpush

resources/views/dashboard/Invoices/GroupInvoices/delete.blade.php
{{-- delete section --}}
{{-- edit section --}}



<!-- Modal -->
<div class="modal fade" id="delete{{$service->id}}" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel{{ $service->id }}" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel{{ $service->id }}">delete Single Invoice</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <form method="POST" action="{{ route('SingleInvoices.destroy',[$service->id]) }}">
            {{method_field('delete')}}

            {{ csrf_field() }}
            @csrf
        <div class="modal-body">

             <input type="hidden" name="id" value="{{$service->id}}">
             <h5>Are You Sure You Want To Delete This SingleInvoices?</h5>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-danger">Delete</button>
        </div>
    </form>
      </div>
    </div>
  </div>

resources/views/dashboard/Invoices/GroupInvoices/index.blade.php
@extends('layouts.dashboard.master')

@section('title')
  sections table
@endsection

@push('css')
<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
<link href="https://cdn.datatables.net/2.0.4/css/dataTables.bootstrap4.css" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous">

    <style>
        body {
            background-color: #fff;
        }
        .nav li a {
            color: white !important;
        }
    </style>
@endpush

@section('content')
        @include('layouts.dashboard.main-headerbar')

    <main class="main mt-5 pt-3">
        <section>
            <div class="container-fluid">
                <div class="row ">
                    @include('layouts.dashboard.main-sidebar')
                    <div class="col-10 col-sm-10  col-md-10 col-lg-10 col-xl-10 py-3 mt-3">
                        <button type="button" class="btn btn-success mb-3">
                            <a href="{{route('SingleInvoices.create')}}">Add Invoice</a>

                          </button>

                        <table id="example" class="table table-striped table-bordered" style="width:100%">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Service Name</th>
                                    <th>Patient Name</th>
                                    <th>invoice date</th>
                                    <th>Doctor Name</th>
                                    <th>Section</th>
                                    <th>price</th>
                                    <th>discount</th>
                                    <th>Tax</th>
                                    <th>total Tax</th>
                                    <th>total</th>
                                    <th>group</th>
                                    <th>Type</th>
                                    <th>Oprations</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($SingleInvoices as $service)
                                <tr>
                                    <td>{{$service->id}}</td>
                                    <td><a href="">{{$service->service->name}}</a></td>
                                    <td>{{$service->patient->full_name}}</td>
                                    <td>{{$service->invoice_date}}</td>
                                    <td>{{$service->doctor->full_name}}</td>
                                    <td>{{$service->section->name}}</td>
                                    <td>{{$service->price}}</td>
                                    <td>{{$service->discount_value}}</td>
                                    <td>{{$service->tax_rate}}</td>
                                    <td>{{$service->tax_value}}</td>
                                    <td>{{$service->total_with_rate}}</td>
                                    <td>{{$service->group->name}}</td>
                                    <td>
                                        @if ($service->type=='1')
                                            {{'آجل'}}
                                        @else
                                            {{'نقدي'}}
                                        @endif

                                    </td>


                                    <td>
                                        <button type="button" class="btn btn-primary" > <a href="{{route('SingleInvoices.edit',[$service->id])}}"><i class="bi bi-pencil-fill"></i></a></button>
                                        <button type="button" class="btn btn-danger"  data-toggle="modal" data-target="#delete{{$service->id}}"> <i class="bi bi-trash3-fill"></i></button>
                                    </td>
                                </tr>
                                @endforeach

                            </tbody>

                        </table>
                    </div>
                    {{-- @include('dashboard.Invoices.SingleInvoices.add') --}}
                    @foreach ($SingleInvoices as $service)
                         {{-- @include('dashboard.Invoices.SingleInvoices.edit') --}}
                         @include('dashboard.Invoices.SingleInvoices.delete')
                    @endforeach

                </div>

            </div>
        </section>

    </main>
@endsection


@push('scripts')
<script defer src="https://code.jquery.com/jquery-3.7.1.js"></script>
    <script defer src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script defer src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script defer src="https://cdn.datatables.net/2.0.4/js/dataTables.js"></script>
    <script defer src="https://cdn.datatables.net/2.0.4/js/dataTables.bootstrap4.js"></script>
    <script>
$(document).ready(function() {
           new DataTable('#example');
        });
    </script>
@endpush